// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhdvA3LWfqNruBSd_9pcVIjUhmnJO4uWs',
    appId: '1:68174194784:web:2e6ad20a3984f4c870bb05',
    messagingSenderId: '68174194784',
    projectId: 'shinhan-hackerton',
    authDomain: 'shinhan-hackerton.firebaseapp.com',
    storageBucket: 'shinhan-hackerton.appspot.com',
    measurementId: 'G-SMLQR1NZHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa7_7WTqWrE33VVe04El48dynNYlTJumI',
    appId: '1:68174194784:android:63dd03f71319a8f370bb05',
    messagingSenderId: '68174194784',
    projectId: 'shinhan-hackerton',
    storageBucket: 'shinhan-hackerton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARc4gwkRz4kXX9_6Xu6bociPcYA8pC1cY',
    appId: '1:68174194784:ios:f6508eaab91eb33570bb05',
    messagingSenderId: '68174194784',
    projectId: 'shinhan-hackerton',
    storageBucket: 'shinhan-hackerton.appspot.com',
    iosBundleId: 'com.example.frontend',
  );
}
